categories:
  - name: 'Conductas contrarias a la convivencia'
    serious: false
    behaviors:
      - 'Perturbación del normal desarrollo de las actividades de clase'
      - 'Falta de colaboración sistemática en la realización de las actividades'
      - 'Impedir o dificultar el estudio a sus compañeros'
      - 'Faltas injustificadas de puntualidad'
      - 'Faltas injustificadas de asistencia a clase'
      - 'Actuaciones incorrectas hacia algún miembro de la comunidad educativa'
      - 'Daños en instalaciones o docum. del Centro o en pertenencias de un miembro'

  - name: 'Conductas gravemente perjudiciales para la convivencia'
    serious: true
    behaviors:
      - 'Agresión física a un miembro de la comunidad educativa'
      - 'Injurias y ofensas contra un miembro de la comunidad educativa'
      - 'Acoso escolar'
      - 'Actuaciones perjudiciales para la salud y la integridad, o incitación a ellas'
      - 'Vejaciones o humillaciones contra un miembro de la comunidad educativa'
      - 'Amenazas o coacciones a un miembro de la comunidad educativa'
      - 'Suplantación de la personalidad, y falsificación o sustracción de documentos'
      - 'Deterioro grave de instalac. o docum. del Centro, o pertenencias de un miembro'
      - 'Reiteración en un mismo curso de conductas contrarias a normas de convivencia'
      - 'Impedir el normal desarrollo de las actividades del centro'
      - 'Incumplimiento de las correcciones impuestas'

  - name: 'Otras'
    serious: false
    behaviors:
      - 'Las descritas con detalle más abajo'
